### ISSUE TITLE
Add 3 letter country codes to tdor dataset

### ISSUE THREAD

**Issue by hturner** [CaRdiffR/tdor#14]
As suggested by @jas1, add 3 letter code for countries (iso_a3). 

This should be done in the script that prepares the raw data: https://github.com/CaRdiffR/tdor/blob/master/data-raw/tdor.R

**Comment by mbytc1** [comment]
library(WDI)
library(countrycode)
df_joined <- df_raw %>% mutate(country_code = countrycode(Country, "country.name", "iso2c"))

**Comment by hturner** [comment]
Thanks @mbytc1. This revealed a typo in one of the source files (Columbia vs Colombia) but otherwise was straight-forward to apply to the tdor data and is now included in the package.
